### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by imomin** [evantahler/ah-resque-ui#19]
Thanks for creating resque-ui, I am trying to make it work on mac but I cannot. Not sure what I am missing here. I took following steps, since the instructions on readme page didn't work for me.
In the project folder, execute below command.

1) `npm install actionhero --save`
2) `node ./node_modules/.bin/actionhero generate`
3) `npm install ah-resque-ui  --save`
4) `node ./node_modules/.bin/actionhero link --name ah-resque-ui` (npm run ... give missing script: ./node_modules/.bin/actionhero error)
5) finally `node ./node_modules/.bin/actionhero start`

No code is injected in routes.js and http://localhost:8080 shows the default actionhero page with "CONGRATULATIONS!" message.

What am I missing?

**Comment by evantahler** [comment]
Those look like the proper steps!

I cannot reproduce the error you noted in #6.  Can you share any more information about your system (node version, npm version, etc)?

There should be no visible changes to config/routes.js.  Visit `http://localhost:8080/resque` in your browser to see the plugin

**Comment by imomin** [comment]
Going to http://localhost:8080/resque  worked!
Looks like I did everything correctly. Just wasn't sure how to get to it. 
Thanks for updating Readme.
