### ISSUE TITLE
Remove JS alert

### ISSUE THREAD

**Issue by nathanbowser** [evantahler/ah-resque-ui#2]
@evantahler First of all, I'm replacing the ruby version of the resque web app with this project, and I'm pretty jazzed, so thank you.

the old school JavaScript `alert(..)` is driving me insane as I'm developing some changes. Thoughts on replacing it with a `console.error` or an alert in the dom?

**Comment by evantahler** [comment]
yeah... me too :D

**Comment by evantahler** [comment]
solved by https://github.com/evantahler/ah-resque-ui/pull/3

**Comment by evantahler** [comment]
v0.0.3 is up
