### ISSUE TITLE
TypeError: Cannot convert undefined or null to object.

### ISSUE THREAD

**Issue by sallespro** [evantahler/ah-resque-ui#22]
hi, i have setup a standard AH install with the plugin, 
action `resqueDetails` returns 200 but the plugin UI shows a Danger : TypeError: Cannot convert undefined or null to object.
i enabled a worker to see if would resolve. the error persists coming from somewhere in this render `      (0, _keys2.default)(this.state.stats).map(function (k) {` below

```
	  render: function render() {
...
	            { className: 'table table-hover' },
	            _react2.default.createElement(
	              'tbody',
	              null,
	              (0, _keys2.default)(this.state.stats).map(function (k) {
	                var v = _this4.state.stats[k];
	                if (k.indexOf(':') > 0) {
	                  return null;
	                }
```

**Comment by sallespro** [comment]
now i tried to build resque-ui but might be missing some webpack loader ?
```
webpack --optimize-dedupe --progress

Hash: c848527f64a5353b8e14
Version: webpack 1.13.3
Time: 103ms
    + 1 hidden modules

ERROR in ./public-src/app.jsx
Module parse failed: /home/user/ah/node_modules/ah-resque-ui/public-src/app.jsx Unexpected token (14:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (14:2)
```

**Comment by evantahler** [comment]
The solve is here https://github.com/evantahler/ah-resque-ui/commit/ee14ee341e9fa39402dc626f31dba2466b494110 if you have never run a worker against this redis instance, you'll have no stats returned.

**Comment by evantahler** [comment]
v0.1.1 is up !

**Comment by evantahler** [comment]
I'm not sure why you can't build it yourself... did you install all the dev-dependancies?

**Comment by sallespro** [comment]
ok, the ui runs fine. Not sure about the build failing with webpack. Shouldn't we need `presets: ['es2015','react']` to transform .jsx in `webpack.config.js` ?

**Comment by evantahler** [comment]
That's here https://github.com/evantahler/ah-resque-ui/blob/master/.babelrc
