### ISSUE TITLE
How can I run this plugin separately to add things to it?

### ISSUE THREAD

**Issue by hazemhagrass** [evantahler/ah-resque-ui#34]
Hi @evantahler 
I was thinking to add more analytics to your plugin but don't know how to run it separately.

**Comment by evantahler** [comment]
This is an ActionHero plugin, so it requires a running ActionHero server to be mounted within. 
Are you asking about other ways to monitor resque directly, perhaps via the `redis-cli` command line tool? 

You can look at the `actions` in this project to see *what* is being monitored

**Comment by hazemhagrass** [comment]
I see that you have 2 folders for public, one of them called public-src, I see that it will be changed somehow to public . How can I generate public folder again?

**Comment by evantahler** [comment]
This is a react project.  `public-src` is compiled into `public` via webpack

**Comment by hazemhagrass** [comment]
perfect thanks.
