### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by hazemhagrass** [evantahler/ah-resque-ui#35]
Hi @evantahler 
Sometimes /rescue url is not working.
<img width="977" alt="screen shot 2016-12-04 at 3 01 33 pm" src="https://cloud.githubusercontent.com/assets/3625423/20866304/0bf983f6-ba33-11e6-903d-b95ac04679bb.png">

**Comment by evantahler** [comment]
you will need to provide a lot more information here:
- What OS
- What node version
- What redis version
- What do you need to do *specifically* for the site to stop showing up, including steps to reliably reproduce the problem.

**Comment by hazemhagrass** [comment]
@evantahler here we go

- what version of actionhero are you using?
15.3.0
- what version of redis?
3.2
- what OS?
Ubuntu 16.04
- Is the scheduler enabled?
Yes

Note: no specific scenario, it is happening randomly.

**Comment by evantahler** [comment]
In your screenshot, the URL is spelled wrong. `/resQue
`

**Comment by hazemhagrass** [comment]
Ops.. thanks
