### ISSUE TITLE
Page freeze when loading several failed jobs

### ISSUE THREAD

**Issue by bayssmekanique** [evantahler/ah-resque-ui#38]
When loading several failed jobs (38 in our instance), the entire page freezes until request is completed.

No console errors (aside from React Dev messages) and the request eventually returns (after 2 minutes).

**Comment by evantahler** [comment]
There is the potential for a lot of data to be transmitted here, based on the size of your job payload and the error trace.   By default, the page will try to load 100 failed jobs before pagination https://github.com/evantahler/ah-resque-ui/blob/master/actions/ah-resque-ui.js#L150-L177.  You can change this in either the action's default or in the font-end's request. 

When you have the page open, look at your network requests tab in chrome and look the `resqueFailed` request.  Where is that 2 minutes being sent?  Is it 2 min waiting for the server to send data to the browser, 2 min for the browser to parse and render that data, etc.

**Comment by bayssmekanique** [comment]
Issue was the result of large resque tasks.

Refactored to move data out of task and not long have issues.
